dist: trusty
sudo: false
language: c
compiler:
    - clang
    - gcc
script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target
    - ctest -V --schedule-random
